### ISSUE TITLE
Expanding beyond TCGA datasets

### ISSUE THREAD

**Issue by shivaprasad-patil** [owkin/PyDESeq2#10]
Hi, Thank you for the implementation, it's great.

I would love to use the package as it is in Python but on my datasets to run differential expression analysis with mostly multi-factor designs. I am sure you must be working on this as the use is currently limited to TCGA datasets and 2 level designs. 

Any ideas when these things would be implemented?
I am excited to finally use a Python package to perform differential expression analysis rather than using it via rpy2.

Thanks.

**Comment by BorisMuzellec** [comment]
Hi @shivaprasad-patil, thank you for your interest in our work!

Unfortunately PyDESeq2 only supports single-factor designs for now, but we plan to implement multi-factor designs shortly. Things might slow down because of end-of-year holidays but we'll definitely start working on it in January.

As for the data, although we provided a helper function (`utils.load_data`) for TCGA data, PyDESeq2 isn't really limited to TCGA datasets – as long as you provide raw counts (one column per gene, indexed by samples), and a clinical data (indexed by samples with a column corresponding to your design factor) in the form of a pandas DataFrames, it should work, c.f. the doc of the `DeseqDataSet` class.

Hope this answers your questions. Hopefully this will be clearer once we build the documentation in a more readable manner!

**Comment by shivaprasad-patil** [comment]
Hi, Thank you for the quick response. Looking forward to the new implementation.
