### ISSUE TITLE
[BUG] `pydeseq2.ds.DeseqStats.lfc_shrink` gives wrong log2FoldChange signs

### ISSUE THREAD

**Issue by PauBadiaM** [owkin/PyDESeq2#121]
**Describe the bug**
When performing LFC shrinkage, the new version seems to flip the reference it uses. I've observed that the obtained `log2FoldChange` have opposite signs as the original contrast, which creates an inconsistency with the sign of `stat`.

**To Reproduce**
You can reproduce this bug with `pydeseq2 >= 0.3.1`. Here's a reproducible example:
```python
import pandas as pd
import numpy as np
from anndata import AnnData
from pydeseq2.dds import DeseqDataSet
from pydeseq2.ds import DeseqStats

# Build toy data, note that G1 should be up in healthy, G2 does not change and G3 should be up in disease
var = pd.DataFrame(index=['G1', 'G2', 'G3'])
X = pd.DataFrame(
    [[16., 7., 12.],
     [22., 6., 1.],
     [10., 8., 30.],
     [3., 6., 20.],
     [1., 5., 17.]], columns=var.index
)
obs = pd.DataFrame(
    [['healthy'],
     ['healthy'],
     ['disease'],
     ['disease'],
     ['disease']], columns=['condition'], index=['S1', 'S2', 'S3', 'S4', 'S5']
    )
adata = AnnData(X, obs=obs, var=var, dtype=np.float32)

# Build DESeq2 object
dds = DeseqDataSet(
    adata=adata,
    design_factors='condition',
    refit_cooks=True,
    n_cpus=8,
)

# Compute LFCs
dds.deseq2()

# Extract contrast between disease vs healthy
stat_res = DeseqStats(dds, contrast=["condition", 'disease', 'healthy'], n_cpus=8)

# Compute Wald test
stat_res.summary()

# Store results before shrink
before_shrink = stat_res.results_df

# Assert that logFCs should have the same sign than stat
assert np.all(np.sign(before_shrink['log2FoldChange']) == np.sign(before_shrink['stat']))

# Shrink LFCs
stat_res.lfc_shrink(coeff='condition_healthy_vs_disease')

after_shrink = stat_res.results_df

# Assert that logFCs should have the same sign than stat
assert np.all(np.sign(after_shrink['log2FoldChange']) == np.sign(after_shrink['stat']))
```

**Expected behavior**
After LFC shrinkage, `log2FoldChange` should have the same sign than `stat`.

**Screenshots**
Before shrinkage:
![image](https://user-images.githubusercontent.com/44896790/234716907-9d16716b-b864-47f3-a22f-06e867ccaefc.png)

After shrinkage:
![image](https://user-images.githubusercontent.com/44896790/234716974-68b6b232-0926-47c5-a221-dc76ea73f8f5.png)

**Desktop (please complete the following information):**
 - OS: linux

**Additional context**
May I ask why now the method `pydeseq2.ds.DeseqStats.lfc_shrink` requires `coeff`? Before (between version `0.3.0` and `0.3.1`) it could be run based on the contrast specified already in the `DeseqStats` object. Now you need to manually check `stat_res.LFC` for the name which feels weird.

I'm aware that if you provide `ref_level=['condition', 'healthy']` to the previous `DeseqDataSet` it will work but then there are two times where the contrast needs to be specified and if there are discrepancies, like here, errors will rise. IMO it makes more sense to specify the contrast at the `DeseqStats` level instead of the `DeseqStats` one.

**Comment by BorisMuzellec** [comment]
Hi @PauBadiaM, thanks for reporting this bug.

What seems to be happening here is that `lfc_shrink` displays the results as per `stat_res`'s contrast attribute `["condition", "disease", "healthy"]`, even though the `coeff` argument of `lfc_shrink` (`condition_healthy_vs_disease`) goes opposite ways. A quick intermediate fix would be to check that the ordering ref_level / test_level match and if not change the sign accordingly. This would work for 2-level factors.

This change in `lfc_shrink` was introduced when we added support for n-level multifactor analysis. The underlying issue is that it is possible to compute `DeseqStats` LFCs for any contrast without refitting `DeseqDataSet`'s LFCs, even if the contrast doesn't match the LFC coefficient of `DeseqDataSet`, but (AFAIK) it's not straightforward to shrink LFCs with an `apeglm` prior when `DeseqDataSet` does not have the right coefficient. My understanding is that this is why you can't provide a contrast in `DESeq2` either for `apeglm` LFC shrinking either (only a coeff).

As a first fix I'll try to make sure that the display of `lfc_shrink` results match its `coeff` (here it should be "condition healthy vs disease"), and if not and if it's a 2-level factor that's been reversed, change the sign.

Another improvement could be to allow `coeff=None` to be passed to `lfc_shrink` (which would shrink the `DeseqDataSet` coeff by default).

For n-level factors I'm not sure how to improve `lfc_shrink` without re-running the `DeseqDataSet` pipeline  when coeffs don't match. I'll try to think about it, I'm open to suggestions :).

**Comment by PauBadiaM** [comment]
Ahhh I see! It makes sense then to ask for it twice, nice that n-level factors are being implemented! Mhmm, it's hard to come up with a good solution, maybe throwing an error if they do not match and asking to rerun `DeseqDataSet` with the proper reference? BTW, thanks for the fast reply.
