### ISSUE TITLE
Is there code for the default dispersion plot? plotDispEsts in DESeq2

### ISSUE THREAD

**Issue by gdolsten** [owkin/PyDESeq2#124]
plotDispEsts is useful to examine the dispersion fit in DESeq2, including the MLE dispersion and the MAP dispersion, is there a function for automatically generating this? I haven't seen it

**Comment by BorisMuzellec** [comment]
Hi @gdolsten, there isn't a `plotDispEsts` equivalent yet, so those plots have to be generated manually from 
`dds.varm["genewise_dispersions"]` (those  are MLE) `dds.varm["MAP_dispersions"]` for now (e.g. with [matplotlib.pyplot.scatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html)).

This would be a nice feature to have but I probably won't have time for it in the near future. I'm happy to help anyone who would like to open a PR though :).

**Comment by emmcauley** [comment]
@BorisMuzellec can you help me understand what I might be missing in the below plot, so that I can potentially open a PR on this issue? 

Based on the documentation, I expect:

-estimated dispersions are stored in dds.varm['genewise_dispersions'] 
-fitted dispersions are stored in dds.varm['fitted_dispersions']
-final dispersions are stored in dds.varm['dispersions']
-normed means are stored in dds.varm['_normed_means']

Is my understanding correct? I am using data from an R-based DESeq2 tutorial but getting a different plot in PyDESeq2 (but I can get the correct plot if I pull it up in RStudio). See below -- it looks like the `final` dispersions are off. Thanks!

Tutorial can be found [here](https://github.com/hbctraining/DGE_workshop/blob/master/lessons/04_DGE_DESeq2_analysis.md)

### Plot I'm getting:
<img width="887" alt="Screen Shot 2023-05-31 at 4 32 46 PM" src="https://github.com/owkin/PyDESeq2/assets/22733781/e7ea1354-4115-43d1-8d60-1d12128e1198">

### Plot I should be getting: 
![R_DESeq2_DispEsts](https://github.com/owkin/PyDESeq2/assets/22733781/0fb522c8-9079-4a7e-8029-4f567dcca918)

**Comment by emmcauley** [comment]
More details:
- Running pydeseq2  version 0.3.3 from bioconda (`pyhdfd78af_0`)
- Counts data I used is [here](https://raw.githubusercontent.com/hbc/NGS_Data_Analysis_Course/master/sessionIII/data/Mov10_full_counts.txt)
- Metadata I used is [here](https://raw.githubusercontent.com/hbc/NGS_Data_Analysis_Course/master/sessionIII/data/Mov10_full_meta.txt) 
-

**Comment by BorisMuzellec** [comment]
Hi @emmcauley, thanks a lot for having a go at implementing dispersion plots :) !

> Based on the documentation, I expect:
>
> -estimated dispersions are stored in dds.varm['genewise_dispersions']
> -fitted dispersions are stored in dds.varm['fitted_dispersions']
> -final dispersions are stored in dds.varm['dispersions']
> -normed means are stored in dds.varm['_normed_means']

Yes, that's correct.

You can also access MAP dispersions (`dds.varm['fitted_dispersions']`), the difference with with final dispersions being that estimated dispersions that are too far above the fitted curve are kept as is in the final estimate, and not shrunk (those are represented as blue-circled dots in the plot you are using as a reference).

Regarding code organization, I suggest writing most of the code in `utils.py`, and adding a wrapper method in `dds.py` that users would be able to call using e.g.

```
dds = DeseqDataset(...)
dds.deseq2()
dds.plot_dispersions()
``` 

Let me know if I can help with anything!

**Comment by emmcauley** [comment]
@BorisMuzellec I've opened PR #137, looking forward to your feedback.

**Comment by BorisMuzellec** [comment]
Thanks @emmcauley for your contribution! I'm closing this issue as #137 has been merged.
