### ISSUE TITLE
Factoring out the core implementation with a `DESeqImplementation` class

### ISSUE THREAD

**Issue by adamgayoso** [owkin/PyDESeq2#187]
Thank you for porting deseq to python, this is a great implementation!

I'm interested in factoring out some of the core optimization routines into their own class so that alternative multiprocessing routines can be used in a more straightforward way.

For example, a chunk of code like this https://github.com/owkin/PyDESeq2/blob/8fbcc2faf744518852c90552242a5049f5d9c9c8/pydeseq2/ds.py#L427-L449

could be placed inside a class like

```
class DESeqImplementation:

    def __init__(verbosity, batch_size):
        # ...

    def lfc_shrink_nbinom_glm(design_matrix, counts, ...) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
       # core routine
```

along with the `wald_test`, `irls`, `fit_alpha_mle`, etc.

the implementation class would then be a keyword arg to the `__init__` of `DeseqStats` and `DeseqDataSet` and facilitate multiple possible backends for inference.

**Comment by adamgayoso** [comment]
So I have such an implementation and am happy to share. I split out every routine that could be accelerated with multiprocessing so that users can write different backends.

**Comment by BorisMuzellec** [comment]
Hi Adam, thanks!

I think this is a great suggestion. The only thing I would be worried about is how do we make sure that the different routines are actually optimizing the same functions (i.e. are based on a correct formulation of the likelihood, etc.), if this is even possible.

Also we should be aware that this could bring PyDESeq2's results a little further away from DESeq2's. E.G. for LFCs we chose to reproduce DESeq2's implementation by using IRLS, but from a mathematical optimization perspective IRLS is a bit weird (kind of like a Newton method with a diagonal regularization on the Hessian, or Newton on a ridge problem but without the ridge term in the gradient) - it's not even guaranteed to converge. If we used another solver, it could probably be more efficient, but we could get results that are a bit different.

That being said, I'm super interested in having a look at the code you write, especially since @umarteauowkin and @omardrwch from our team have been experimenting with jax and PyDESeq2 lately :)

**Comment by adamgayoso** [comment]
Hi @BorisMuzellec. I will make a PR soon.

Certainly my abstraction can be improved, but I tried to isolate input and output types of the main routines. Whether anyone would use this to implement something that is "more optimal" or just plain faster is up to the community! 

The code in this codebase is certainly good enough to test reproducibility at the basic "make it faster" level. If the abstraction is good then folks can play with different kinds of optimization.
