### ISSUE TITLE
DeseqDataSet on Normalized Counts

### ISSUE THREAD

**Issue by dstrib** [owkin/PyDESeq2#194]
Hi!

I wanted to ask about the possibility of a new feature. I would like to normalize my data, output the normalized counts, cull my genes to a particular minimum count, and then initialize and perform a DeseqDataSet analysis. 

My rationale is that if I perform the minimum gene amplitude cutoff before normalization, this does not use all possible reads for normalization and may miss the effects of collections of low-count alignments. However if if use a different set of reads for normalization (to output normalized counts) and for DE (for statistical testing) then these datasets will not correspond.

My proposed solution would be an option in the DeseqDataSet(normalize=False) for if the input counts have already been normalized with pydeseq2.preprocessing.

Thanks!

**Comment by BorisMuzellec** [comment]
Hi @dstrib, sorry for the late reply.

From what I understand I think you can achieve this by

1. Performing normalisation with `dds.fit_size_factors()` (which will populate `dds.layers["normed_counts"]`) or `VST` if you prefer
2. Selecting the genes you want to keep from `dds.layers["normed_counts"]`
3. Subsetting the dds (`dds[:, genes_to_keep]`)

Would that work?

**Comment by dstrib** [comment]
Thanks for the reply!
I think it would, but to be sure then what would the next step be to run the DE analysis as before?

**Comment by BorisMuzellec** [comment]
You'd have to run the steps one by one as in [this example](https://pydeseq2.readthedocs.io/en/latest/auto_examples/plot_step_by_step.html#sphx-glr-auto-examples-plot-step-by-step-py), because running `dds.deseq2()` would overwrite the size factors. It's a bit less straightforward...

That being said I'm not sure there's much to gain from using low-count genes that will eventually be filtered out from the analysis. The default normalization method in PyDESeq2, median of ratios, computes a geometric mean across samples for each gene *with no zero count anywhere*, renormalizes with this mean, and then takes the median of normalized counts within each sample.

The key thing here is that genes that will be filtered out likely won't be taken into account anyway, because they probably have a zero for at least one sample.

**Comment by dstrib** [comment]
Thanks for the response!
That’s a good point. In my specific case I’m doing a pretty stringent read count cutoff, so there should be a nontrivial difference when the low-count reads are also used.
