### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kavousisiavash** [owkin/PyDESeq2#339]
**Describe the bug**
Hi i get this error
TypeError: DeseqDataSet.__init__() got an unexpected keyword argument 'design'

when run this part of documentation : 

![image](https://github.com/user-attachments/assets/3aa0da94-2576-44af-82da-216a2c874cb2)

https://pydeseq2.readthedocs.io/en/latest/auto_examples/plot_step_by_step.html#sphx-glr-auto-examples-plot-step-by-step-py

If I remove the design, the code will run, but this has consequences that you know better. How should I solve this problem?

**Comment by BorisMuzellec** [comment]
Hi @kavousisiavash, indeed, this is because this feature is only available in the `0.5.0-rc1` pre-release that was published yesterday.

You can either:
- install the latest version using the `--pre` flag (`pip install --pre pydeseq2`)
- or use the version you have currently installed and refer to the "stable" version of the docs: https://pydeseq2.readthedocs.io/en/stable/auto_examples/plot_minimal_pydeseq2_pipeline.html

You should be able to see (and choose) which version of the docs you are reading from the bottom-right corner of the read-the-docs page:

<img width="215" alt="Capture d’écran 2024-11-20 à 14 25 57" src="https://github.com/user-attachments/assets/62599231-85f4-46c2-8004-da4dda0f62d2">

**Comment by kavousisiavash** [comment]
Hello
Thanks for your help
I first ran the code you introduced
Then I checked the version via the command prompt
But the problem was not solved.

![image](https://github.com/user-attachments/assets/fd65a53a-db64-4e8d-9567-9bf506c2b91c)

![image](https://github.com/user-attachments/assets/597208f1-7c60-4865-b9bf-16773078c4a3)

**Comment by BorisMuzellec** [comment]
@kavousisiavash you still have v 0.4.12 installed. If you want to use the same environment, you need to use the `--upgrade` flag. (`pip install --upgrade --pre pydeseq2`)

**Comment by BorisMuzellec** [comment]
I'm closing because it seems like this is solved, don't hesitate to re-open if not

**Comment by serenalotreck** [comment]
Hi @BorisMuzellec , I'm having the same issue and I ran `pip install --upgrade --pre pydeseq2` in my conda environment, but it didn't actually upgrade the package, and `pip install pydeseq2==0.5.0` gives `ERROR: No matching distribution found for pydeseq2==0.5.0`, as 0.4.12 is the latest version that pip is aware of even though [the docs I'm reading](https://pydeseq2.readthedocs.io/en/stable/usage/installation.html) say they're for 0.5.0.

Not sure if that merits a separate issue, but would appreciate some help!

**Comment by BorisMuzellec** [comment]
@serenalotreck are you by any chance using python 3.9? If so, so it could be that `0.4.12` is the latest version compatible with your environment as python 3.9 is no longer supported starting from `pydeseq2 0.5.0`


PS: you shouldn't need the `--pre` flag anymore because `0.5.0` is now a full release :)

**Comment by serenalotreck** [comment]
You're totally right, I thought I was running 3.10 but I didn't actually check 🤦 😂 That seems to have fixed it, thanks!
