### ISSUE TITLE
Cannot import 'load_example_data'

### ISSUE THREAD

**Issue by alberto-mora** [owkin/PyDESeq2#50]
After installing pydeseq2 in a new conda environment. When importing, this error appears:

ImportError: cannot import name 'load_example_data' from 'pydeseq2.utils' (/home/vant/miniconda3/envs/py38/lib/python3.8/site-packages/pydeseq2/utils.py)

**Comment by BorisMuzellec** [comment]
Hi @alberto-mora, can you install pydeseq2 again from pip (and check you have version 0.2.1)?

`pip install --upgrade pydeseq2`

This function was renamed from `load_data` to `load_example_data`, looks like it still goes by its old name in the version you have installed.

**Comment by maikia** [comment]
Hi @alberto-mora if you still have the same issue after following the instructions of @BorisMuzellec could you give us a snippet of code which you are using so that we can reproduce it?

I was unable to reproduce it with the code:

`from pydeseq2.utils import load_data` 
or in a new version:
`from pydeseq2.utils import load_example_data` ?

Thanks
