### ISSUE TITLE
[BUG] DeseqDataSet._replace_outliers ignores whether cohorts have enough samples

### ISSUE THREAD

**Issue by LawrenceGordon** [owkin/PyDESeq2#69]
Hello again!

I have a sample set where I only have 3 replicates each of my control and test factors, which by default behavior should not have enough samples to allow refitting. However, when I run PyDESeq2, there is a cooks refitting performed (noted by the printing of "Refitting n outliers."

The sample check is first performed by the `n_or_more` variable in the  `_replace_outliers` function of the `DeseqDataSet` class, which returns the correct dataframe. Next, `self.replaceable` is calculated and also gives the correct dataframe of (n_samples, 1) with all False values (i. e. do not replace any values in this sample).

I believe the error lies in the indexing used in line 688:
`self.counts_to_refit[idx[self.replaceable].loc[:, self.replaced]]`

`idx[self.replaceable]` returns a dataframe of 0 rows x n_genes columns and thus `idx[self.replaceable].loc[:, self.replaced]` returns the genes from `self.replaced`, which can have genes regardless of sample replicate numbers.

Under conditions in which there are enough replicates for all samples, the dataframe would be in the shape (n_samples, n_genes_to_replace). In the case of there not being enough replicates, the dataframe shape is (0, n_genes_to_replace) which is just column headers.

However, in the final step of indexing `self.counts_to_refit`, a dataframe is returned of shape (n_samples, n_genes_to_replace) regardless of whether the values should be replaced or not.

I am having trouble pinning down this issue further but I hope this is enough info to help!

Thanks,
Lawrence

**Comment by BorisMuzellec** [comment]
Hi Lawrence,

Thank you very much for reporting this behaviour and for your efforts to pinpoint the issue.

I have been able to reproduce the issue indeed. However, upon further investigation it seems that in this setting (3 samples in the control and 3 in the test) no quantities are actually changed when calling `self.refit()`, even though the "Refitting n outliers" message suggests otherwise.

The bug seems to come from the fact that the `self.replaced` attribute (which tracks which genes have outlier counts) does not take into account whether cohorts have enough samples to refit. Hence, in your case `self.refit()` will print  "Refitting n outliers" and run `self._refit_without_outliers()` even though no values are actually changed in the process, which is unexpected behaviour (we should report 0 outliers and skip `self._refit_without_outliers()`).

There could be an impact on `DeseqStats`'s behaviour though. I haven't checked. 

I'll open a PR to fix this bug, but merging it might take some time as I'll be away next week. In the meantime, you can also initialise your `DeseqDataSet` with `refit_cooks=False` (and `DeseqStats` with `cooks_filter=False` if needed) to avoid any issues.

Thanks again for your help!

Best,
Boris
