### ISSUE TITLE
[BUG] Save summary data in `ds.py`

### ISSUE THREAD

**Issue by Morteza-M-Saber** [owkin/PyDESeq2#78]
In `summary` method in `ds.py`, the results are displayed rather than being saved.
I think line 209 of `ds.py` should be changed:

> display(self.results_df) -> return(self.results_df)

**Comment by BorisMuzellec** [comment]
Hi @Morteza-M-Saber,

This behaviour is intentional, the idea being that the results can then be accessed through the `results_df` attribute of the `DeseqStats` (`foo.results_df` if your `DeseqStats` object is named `foo`), but this might not be the most convenient.

Would adding an optional `save_path` argument to the `summary()` method such that calling `ds.summary(save_path="foodir/foofile.csv")` would save a csv seem relevant? 

What would be the ideal behaviour according to you?

**Comment by Morteza-M-Saber** [comment]
Thanks @BorisMuzellec ,
I see the logic, however, I feel using `return` has multiple advantages over `display`. First, the tool might be implemented as part of pipeline and displaying the results would not be desired, second, user might want to do additional filtering/trimming based on the summary results. I personally needed to round the returned values and filter genes with certain p-value threshold. By returning the `results_df`, user can perform the additional analysis before finally saving it in desired output.

This is jus a personal thought. The implemented approach provides the information as well.
